file(GLOB SEARCH_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
add_library(search_lib OBJECT ${SEARCH_SOURCES})
target_include_directories(search_lib PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_include_directories(search_lib PRIVATE ${CMAKE_SOURCE_DIR}/../core/include)
target_include_directories(search_lib PRIVATE ${CMAKE_SOURCE_DIR}/../include)
