file(GLOB READING_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
add_library(reading_lib OBJECT ${READING_SOURCES})
target_include_directories(reading_lib PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_include_directories(reading_lib PRIVATE ${CMAKE_SOURCE_DIR}/../core/include)
target_include_directories(reading_lib PRIVATE ${CMAKE_SOURCE_DIR}/../include)
