file(GLOB TOOLS_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
add_library(tools_lib OBJECT ${TOOLS_SOURCES})
target_include_directories(tools_lib PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_include_directories(tools_lib PRIVATE ${CMAKE_SOURCE_DIR}/../core/include)
target_include_directories(tools_lib PRIVATE ${CMAKE_SOURCE_DIR}/../include)
