file(GLOB ANALYSIS_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
add_library(analysis_lib OBJECT ${ANALYSIS_SOURCES})
target_include_directories(analysis_lib PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_include_directories(analysis_lib PRIVATE ${CMAKE_SOURCE_DIR}/../core/include)
target_include_directories(analysis_lib PRIVATE ${CMAKE_SOURCE_DIR}/../include)
