#include "AiSummarizerWidget.hpp"
#include "ApiManager.hpp"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QSplitter>
#include <QApplication>
#include <QClipboard>

AiSummarizerWidget::AiSummarizerWidget(QWidget* parent)
    : QWidget(parent)
{
    setupUI();
}

void AiSummarizerWidget::setupUI() {
    auto* layout = new QVBoxLayout(this);

    // Type selector
    auto* topRow = new QHBoxLayout();
    topRow->addWidget(new QLabel("Summary Type:"));
    typeCombo_ = new QComboBox();
    typeCombo_->addItems({
        "Abstract Summary", "Key Contributions", "Method Summary",
        "Findings Summary", "Critical Review", "Comparison Notes",
        "Research Questions", "Bullet Points"
    });
    connect(typeCombo_, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &AiSummarizerWidget::onTypeChanged);
    topRow->addWidget(typeCombo_, 1);
    layout->addLayout(topRow);

    // Splitter: input | result
    auto* splitter = new QSplitter(Qt::Horizontal);

    // Input
    auto* inputPanel = new QWidget();
    auto* inputLayout = new QVBoxLayout(inputPanel);
    inputLayout->setContentsMargins(0, 0, 0, 0);

    auto* inputLabel = new QLabel("Paper Content");
    inputLabel->setStyleSheet("font-weight: bold; font-size: 12px;");
    inputLayout->addWidget(inputLabel);

    inputEdit_ = new QPlainTextEdit();
    inputEdit_->setPlaceholderText("Paste paper title, abstract, or full text here...");
    inputEdit_->setStyleSheet(
        "QPlainTextEdit { border: 1px solid palette(mid); border-radius: 4px; padding: 8px; }"
    );
    inputLayout->addWidget(inputEdit_);
    splitter->addWidget(inputPanel);

    // Result
    auto* resultPanel = new QWidget();
    auto* resultLayout = new QVBoxLayout(resultPanel);
    resultLayout->setContentsMargins(0, 0, 0, 0);

    auto* resultLabel = new QLabel("AI Summary");
    resultLabel->setStyleSheet("font-weight: bold; font-size: 12px;");
    resultLayout->addWidget(resultLabel);

    resultEdit_ = new QPlainTextEdit();
    resultEdit_->setReadOnly(true);
    resultEdit_->setPlaceholderText("Summary will appear here...");
    resultEdit_->setStyleSheet(
        "QPlainTextEdit { border: 1px solid palette(mid); border-radius: 4px; padding: 8px; "
        "background: #f8fafc; }"
    );
    resultLayout->addWidget(resultEdit_);
    splitter->addWidget(resultPanel);

    splitter->setSizes({400, 400});
    layout->addWidget(splitter, 1);

    // Progress
    progressBar_ = new QProgressBar();
    progressBar_->setVisible(false);
    layout->addWidget(progressBar_);

    // Status
    statusLabel_ = new QLabel("");
    statusLabel_->setStyleSheet("font-size: 11px; color: #64748b;");
    layout->addWidget(statusLabel_);

    // Buttons
    auto* btnRow = new QHBoxLayout();
    btnRow->addStretch();

    copyBtn_ = new QPushButton("Copy Result");
    connect(copyBtn_, &QPushButton::clicked, this, &AiSummarizerWidget::onCopyResult);
    btnRow->addWidget(copyBtn_);

    generateBtn_ = new QPushButton("Generate");
    generateBtn_->setStyleSheet(
        "QPushButton { background: #3b82f6; color: white; padding: 8px 24px; "
        "border-radius: 6px; font-weight: bold; }"
        "QPushButton:hover { background: #2563eb; }"
    );
    connect(generateBtn_, &QPushButton::clicked, this, &AiSummarizerWidget::onGenerate);
    btnRow->addWidget(generateBtn_);

    layout->addLayout(btnRow);
}

void AiSummarizerWidget::setPaperContent(const QString& title, const QString& abstract, const QString& fullText) {
    paperTitle_ = title;
    paperAbstract_ = abstract;
    QString content;
    if (!title.isEmpty()) content += "Title: " + title + "\n\n";
    if (!abstract.isEmpty()) content += "Abstract: " + abstract + "\n\n";
    if (!fullText.isEmpty()) content += fullText;
    inputEdit_->setPlainText(content);
}

void AiSummarizerWidget::onGenerate() {
    QString input = inputEdit_->toPlainText().trimmed();
    if (input.isEmpty()) {
        statusLabel_->setText("Please enter paper content first");
        return;
    }

    progressBar_->setVisible(true);
    progressBar_->setRange(0, 0);
    generateBtn_->setEnabled(false);
    statusLabel_->setText("Generating summary...");

    QString type = typeCombo_->currentText().toLower().replace(" ", "_");

    if (apiManager_) {
        QJsonObject payload;
        payload["text"] = input;
        payload["type"] = type;
        payload["title"] = paperTitle_;
        apiManager_->sendPostRequest("ai/summarize", payload);
    }

    // Placeholder result
    QTimer::singleShot(1500, this, [this, type]() {
        QString summary;
        if (type.contains("bullet")) {
            summary = "• Key finding 1: [AI-generated summary placeholder]\n"
                     "• Key finding 2: [Summary would be generated by backend]\n"
                     "• Method: [Method summary]\n"
                     "• Result: [Result summary]";
        } else {
            summary = QString("[AI-generated %1 summary placeholder]\n\n"
                "In production, this would call the backend AI service to generate "
                "a real summary from the paper content.").arg(type);
        }

        resultEdit_->setPlainText(summary);
        progressBar_->setVisible(false);
        generateBtn_->setEnabled(true);
        statusLabel_->setText("Summary generated");
        emit summaryReady(summary);
    });
}

void AiSummarizerWidget::onCopyResult() {
    QString text = resultEdit_->toPlainText();
    if (!text.isEmpty()) {
        QApplication::clipboard()->setText(text);
        statusLabel_->setText("Copied to clipboard");
    }
}

void AiSummarizerWidget::onTypeChanged(int) {
    // Clear previous result when type changes
    resultEdit_->clear();
    statusLabel_->setText("");
}
